### ISSUE TITLE
Indicator data type

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#4205]
#### Expected Behavior

- Indicator methods at QCAlgorithm.Indicators allow using different data types as inputs for consolidators **and** the indicators themselves 
#### Actual Behavior

- Indicator methods at QCAlgorithm.Indicators do not allow providing a data type and just use the first subscription data type (ordered by `TickType`).
- `Consolidate<T>(Symbol, TimeSpan, Action<T>)` is ignoring the input `<T>` and sending in `TickType` null. Same for `Consolidate<T>(Symbol, Resolution, TickType?, Action<T>)` which even has a `TickType` argument.
    - It seems that as a workaround for this bug we have `Consolidate(Symbol, TimeSpan, Action<TradeBar>)` and `Consolidate(Symbol, TimeSpan, Action<QuoteBar>)`, which are also duplicated for `Resolution` instead of `TimeSpan`
- `ResolveConsolidator`
   - Should allow optionally sending in desired input type for the consolidator 
   - Code path execution duplication
       - `ResolveConsolidator(Symbol symbol, Resolution? resolution)`
           - Calls `GetSubscription()`
           - Calls `ResolveConsolidator(Symbol symbol, TimeSpan? timeSpan)` 
               - Calls `GetSubscription()` **again**
- `GetSubscription()`: Why is it public? It shouldn't be ordering **all** `Subscriptions`
- Custom data consolidator, in the following example `data` sent in to the consolidator is of type `TradeBar` since that is the output of the default used `BaseDataConsolidator`.
```
var symbol = AddData<Bitcoin>("BTC", resolution).Symbol;
var consolidator = CreateConsolidator(TimeSpan.FromDays(1), typeof(Bitcoin));
RegisterIndicator(symbol, new SimpleMovingAverage(10), consolidator, data =>
{
    var type = data.GetType();
    return data.Value;
});
```
#### Potential Solution

- Add and test data type arguments for indicators
- Review, fix and test QCAlgorithm.Indicators methods which are not respecting the provided data type or type of `T`

Update:
- Define default data type per security (currently its the `DefaultDataTypes` collection ordered by TickType), to be used when the data type isn't provided. Today in most cases this is TradeBars, we don't want to break existing behavior when we modify `DefaultDataTypes`.
- Indicators of type `IndicatorDataPoint` which use another input data type
    - Add `dataType` argument to existing indicator helper methods, exmaple: SMA of quotebar spread
    - `RegisterIndicator<T>` implementations should send in typeof(T) to `ResolveConsolidator`
    - Send in the dataType argument to `ResolveConsolidator` to determine the consolidator type to use and the Subscription!
        - Assert dataType inherits from `BaseData`
- Send data type into `WarmupIndicator` method
    - Make a history request just for the required type? either way need to consume dynamically
    - How to consume a dynamic data type from a Slice? -> get by type (requires a small change to expose this method)
- `GetSubscription()`
    - Make it private and should only request and order subscriptions for the target Symbol
- Custom data consolidator: I believe we could create a smarter default consolidator which output is of the custom data type.
- **Note:** Existing API methods using `TickType` seem limited and an abuse of the `TickType` class. It seems they should be using `T dataType where T : BaseData` or `Type dataType` and assert it inherits from `BaseData`
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
> Define default data type per security

Already implemented see `SubscriptionManager.IsDefaultDataType`

> RegisterIndicator<T> implementations should send in typeof(T) to ResolveConsolidator

Solved

> GetSubscription()

Is private

### TODO

> Add dataType argument to existing indicator helper methods, exmaple: SMA of quotebar spread

Feature

> Custom data consolidator

Not sure if already possible, implement example

> Make a history request just for the required type?

Improvement: We could use the `consolidator.InputType` as we do to access the data in the response. See https://github.com/QuantConnect/Lean/issues/6975
